In [1]:
import numpy as np
import pandas as pd
import sklearn as sk

from sklearn.decomposition import PCA

In [7]:
train = pd.read_csv('close_prices.csv', index_col='date')

In [8]:
train.head()

AXP          BA        CAT       CSCO         CVX  \
date                                                                  
2013-09-23  76.440002  117.510002  85.029999  24.270000  125.519997   
2013-09-24  76.070000  119.000000  85.110001  24.139999  124.489998   
2013-09-25  75.989998  118.510002  84.500000  24.430000  124.070000   
2013-09-26  76.320000  119.379997  84.199997  23.770000  123.489998   
2013-09-27  75.889999  118.739998  83.800003  23.330000  122.639999   

                   DD        DIS         GE          GS         HD    ...      \
date                                                                  ...       
2013-09-23  59.409999  64.750000  24.280001  165.250000  75.910004    ...       
2013-09-24  59.319997  64.320000  24.320000  162.970001  76.040001    ...       
2013-09-25  59.319997  64.449997  24.230000  162.309998  75.519997    ...       
2013-09-26  59.509996  65.239998  24.250000  162.289993  76.070000    ...       
2013-09-27  59.009995  65.190002  24.049999  159.850006  75.959999    ...       

                  PFE         PG          T        TRV        UNH         UTX  \
date                                                                            
2013-09-23  28.799999  79.279999  34.220001  86.379997  71.820000  109.419998   
2013-09-24  28.709999  78.620003  34.090000  85.870003  72.320000  110.000000   
2013-09-25  28.490000  77.720001  34.049999  85.980003  71.980003  109.260002   
2013-09-26  28.520000  78.050003  34.230000  85.830002  72.160004  109.660004   
2013-09-27  28.879999  77.209999  33.980000  85.410004  71.989998  109.360001   

                     V         VZ        WMT        XOM  
date                                                     
2013-09-23  196.240005  47.980000  76.419998  87.750000  
2013-09-24  193.339996  47.270000  75.750000  87.360001  
2013-09-25  191.559998  46.950001  74.650002  87.139999  
2013-09-26  193.559998  47.669998  74.620003  87.070000  
2013-09-27  193.050003  47.000000  74.360001  86.900002  

[5 rows x 30 columns]

In [23]:
pca = PCA(n_components=10)

In [38]:
fitted_pca = pca.fit(train.values)

In [39]:
fitted_pca.explained_variance_ratio_

array([0.73897118, 0.11007169, 0.04995088, 0.0287492 , 0.02215448,
       0.01931577, 0.00674853, 0.00614091, 0.00320594, 0.00305611])

In [34]:
sum(fitted_pca.explained_variance_ratio_)

0.988364692910826

In [56]:
sum = 0.
count = 0

for idx, i in enumerate(fitted_pca.explained_variance_ratio_):
    sum += i
    if sum >= 0.9:
        count = idx + 1
        break

In [57]:
count

4

In [40]:
comp = pd.DataFrame(fitted_pca.transform(train.values))[0]

In [52]:
dj_index = pd.read_csv('djia_index.csv', usecols=['^DJI'])

In [54]:
cor = np.corrcoef(comp, dj_index['^DJI'])

In [55]:
cor

array([[1.        , 0.90965222],
       [0.90965222, 1.        ]])

In [58]:
fitted_pca.components_[0]

array([ 1.61383840e-02,  1.20644923e-01, -5.16612711e-02,  5.04842369e-02,
       -1.25859933e-01,  1.14089567e-01,  2.33906290e-01, -6.20513749e-03,
        2.51227032e-01,  2.88996029e-01, -2.64998795e-01,  9.31320168e-02,
        9.13948403e-02,  4.69879340e-02,  2.90549417e-02, -2.61068828e-02,
        3.29615584e-01,  7.13897133e-02,  7.62295699e-02,  2.11888868e-01,
        2.30922941e-02,  7.77316954e-02, -7.20594590e-03,  1.89479745e-01,
        3.21564017e-01,  5.36834873e-02,  5.79683946e-01,  1.09122230e-04,
        8.71614334e-02, -4.29421420e-02])